version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
    allow:
      - dependency-type: direct
    assignees:
      - MorevM
    commit-message:
      prefix: chore
    labels: [dependencies]
    open-pull-requests-limit: 30
